FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy only the necessary files, excluding spynorama
COPY main.py .
COPY ui_app.py .
COPY launcher.py .
COPY api/ ./api/
COPY templates/ ./templates/
COPY medias/ ./medias/
COPY tuto/ ./tuto/
COPY requirements.txt .

# Make the launcher script executable
RUN chmod +x launcher.py

# Use the launcher as the entry point
CMD ["python", "launcher.py"]
