version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./main.py:/app/main.py
      - ./api:/app/api
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./ui_app.py:/app/ui_app.py
      - ./templates:/app/templates
      - ./medias:/app/medias
      - ./tuto:/app/tuto
    depends_on:
      - api
    restart: unless-stopped
