FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy only the necessary files, excluding spynorama
COPY main.py .
COPY api/ ./api/
COPY requirements.txt .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
